def get_temp_row():
    return {
    "COUNTRY_A": ["COL"],
    "LABORATORY": ["HSR"],
    "ORIGIN": ["h"],
    "PATIENT_ID": [70000162],
    "LAST_NAME": ["ARCILA RIOS"],
    "FIRST_NAME": ["AICARDO DE JESUS"],
    "SEX": ["m"],
    "DATE_BIRTH": ["2024-10-28"],
    "AGE": [67],
    "PAT_TYPE": ["adu"],
    "WARD": ["hosmix"],
    "INSTITUT": ["HSR"],
    "DEPARTMENT": ["mix"],
    "WARD_TYPE": ["inx"],
    "SPEC_NUM": [10252215],
    "SPEC_DATE": ["2024-10-27"],
    "SPEC_TYPE": ["se"],
    "LOCAL_SPEC": ["SECRECIONES"],
    "SPEC_CODE": [60],
    "ORGANISM": ["aba"],
    "LOCAL_ORG": ["Acinetobacter baumannii"],
    "ORG_TYPE": ["-"],
    "MRSA": [None], "BETA_LACT": [None], "ESBL": [None], "CARBAPENEM": [None], "INDUC_CLI": [None],
    "X_IAD": [None], "X_ISO": [None], "X_GEN_CARB": [None], "X_APB": [None], "X_EDTA": [None],
    "X_CARBA_NP": [None], "X_MCIM": [None], "AMP_NM": ["<=2"], "SAM_NM": [None], "ATM_NM": [">32"],
    "CZO_NM": [2], "FEP_NM": [6], "CAZ_NM": [1], "CRO_NM": ["<=.25"], "CIP_NM": [None], "CLI_NM": [None],
    "DAP_NM": [4], "ETP_NM": [4], "ERY_NM": [None], "GEN_NM": ["<=1"], "GEH_NM": [None],
    "LVX_NM": [None], "LNZ_NM": [None], "MEM_NM": ["<=.25"], "NAL_NM": [None], "NIT_NM": [None],
    "OFX_NM": [None], "OXA_NM": ["<=4"], "PEN_NM": [None], "TZP_NM": [None], "RIF_NM": [None],
    "TCY_NM": ["<=.5"], "TGC_NM": ["<=1"], "SXT_NM": [None], "VAN_NM": [None], "AMK_NM": [1],
    "CEP_NM": [None], "MAN_NM": [None], "CTX_NM": [None], "CXM_NM": [None], "FOS_NM": [None],
    "MIF_NM": [None], "MUP_NM": [None], "NOR_NM": [None], "TEC_NM": [None], "VOR_NM": [None],
    "AMB_NM": [None], "CAS_NM": [None], "FOX_NM": [None], "CPT_NM": [None], "CZA_NM": [None],
    "CZT_NM": [None], "CHL_NM": [None], "FLU_NM": [None], "IPM_NM": [None], "MFX_NM": [None],
    "STH_NM": [None], "FCT_NM": [None], "AMC_NM": [1], "COL_NM": [None], "MNO_NM": [None],
    "SXT_ND1_2": [None], "AMK_ND30": [None], "IPM_ND10": [None], "CAZ_ND30": [None], "CIP_ND5": [None],
    "ATM_ND30": [None], "MEM_ND10": [None], "ETP_ND10": [None], "PNV_NM": [None], "FOX_ND30": [None],
    "AMX_NM": [None], "CCV_NM": [None], "CTL_NM": [None], "AMP_ND10": [None], "CLI_ND2": [None],
    "ERY_ND15": [None], "PEN_ND10": [None], "TOB_NM": [None], "CTC_NM": [None], "PRI_NM": [None],
    "QDA_NM": [None], "ICL_NM": [None], "OXA_ND1": [None], "VAN_ND30": [None]
}